---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.10.1
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Reshaping and three-dimensional arrays

## One-dimensional arrays

Our usual import:

```{python}
import numpy as np
```

Here is a one-dimensional array:

```{python}
arr_1d = np.arange(6)
arr_1d
```

## Shapes are tuples

Notice the shape:

```{python}
arr_1d.shape
```

What type of thing is the shape?

```{python}
type(arr_1d.shape)
```

A tuple is a basic Python object, like a list, with some small differences.

Where we form a list with square brackets, as in:

```{python}
# A list
my_list = [1, 2, 3]
my_list
```

— we form a tuple with parentheses (round brackets):

```{python}
# A tuple
my_tuple = (1, 2, 3)
my_tuple
```

Like a list, we can get the length of a tuple, and we can index into a tuple:

```{python}
print('Length of the tuple is:', len(my_tuple))
print('tuple element at position 1 is:', my_tuple[1])
```

We can change a list, by replacing the values, adding or removing elements.  Formally, this means a list is *mutable*.   A tuple is *immutable* — we cannot change its elements, or add or remove elements.  For example:

```{python tags=c("raises-exception")}
my_tuple[1] = 99
```

There is also a wrinkle with making a length-1 tuple, because Python interprets this as your usual brackets for arithmetic:

```{python}
# Python interprets this parentheses in arithmetic.
just_a_number = (1)
just_a_number
```

To form a length-1 tuple, you need to disambiguate with an extra comma:

```{python}
short_tuple = (1,)  # Notice the extra comma
short_tuple
```

We will now be using tuples to give our array shapes, although lists will also work.

See {ref}`tuples` for more.

## Reshaping

We can reshape this array to two dimensions using the `np.reshape` function:

```{python}
new_shape = (2, 3)  # New shape, as a tuple.
arr_2d = np.reshape(arr_1d, new_shape)
arr_2d
```

Notice how NumPy used the 1D array elements.  It takes each element from the
1D array, and fills the rows first, and then the columns.

We can reshape back to one dimension.

```{python}
one_d_shape = (6,)  # 1D shape, as a tuple.  Notice extra comma.
arr_2d.reshape(one_d_shape)
```

Here NumPy fetches the data from the *rows first*, and then the columns, to
fill out the elements of the 1D array.

The value `-1` is special for `np.reshape`.  It means, "make a
dimension the size that will use the remaining unspecified elements".   We’ll
see what “unspecified” means soon.  At the moment, "unspecified" is true of
all the elements, so the shape is the same as the number of elements in the 2D
array:

```{python}
np.reshape(arr_2d, (-1,))
```

It is very common to convert a 2 or 3 or N-dimensional array to a 1D array, so
there is a short-cut command for that:

```{python}
np.ravel(arr_2d)
```

You can reshape from one shape, to any other shape, as long as the number of
elements stays the same.  Notice the algorithm NumPy is using to decide which
elements go in which position of the array — rows first, and then columns.

```{python}
np.reshape(arr_2d, (3, 2))
```

Reshape uses -1 as a value to mean the shape value that will use the remaining
unspecified elements.  For example, we could specify that we want the first
dimension to be length 3, and NumPy can work out the second dimension must be
length 2, and the other way round:

```{python}
arr_1d.reshape((3, -1))
```

```{python}
arr_1d.reshape((-1, 2))
```

## Into the third dimension

As mentioned on the [Three-dimensional arrays](arrays_3d.Rmd) page, one-dimensional and two-dimensional arrays are easy to think about. The one-dimensional array is like a row from a table or spreadsheet.  A two-dimensional array has rows and columns, like a table or a spreadsheet.

A three-dimensional array takes a little bit more work to visualize, and get used to.

## Reshaping a three-dimensional array

NumPy uses the same algorithm for reshaping a three-dimensional array:

```{python}
arr_1d_bigger = np.arange(24)
print(arr_1d_bigger)
print(arr_1d_bigger.shape)
```

```{python}
arr_3d = arr_1d_bigger.reshape((2, 3, 4))
arr_3d
```

Here NumPy is showing us the two slices over the first dimension:

```{python}
print(arr_3d[0, :, :])
print(arr_3d[1, :, :])
```

To think about what array this is, imagine tipping the bottom of each 2D array
towards you from the plane of the screen, and look at these tipped planes from
the left, so the 0 sits nearly on top of 12, in the plane of the screen, and 4
sits nearly on top of 16, a little forward of the plane of the screen.

Here are the four “planes” of the array (slices over the third dimension):

```{python}
for i in range(4):
    print(arr_3d[:, :, i])
```

We can reshape to one dimension in the same way as we did for the 2D arrays.

```{python}
arr_3d.reshape(24)
```
```{python}
arr_3d.reshape(-1)
```
```{python}
arr_3d.ravel()
```

To get the elements of the 1D array, NumPy first fetches values across the
last axis (the depth or plane axis), then the second to last (column) axis,
then the first (row) axis.

When reshaping to three dimensions, NumPy fills out the last, then second,
then first dimensions:

```{python}
arr_3d = arr_1d_bigger.reshape((2, 3, 4))
arr_3d
```
