---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.5
---

$\newcommand{L}[1]{\| #1 \|}\newcommand{VL}[1]{\L{ \vec{#1} }}\newcommand{R}[1]{\operatorname{Re}\,(#1)}\newcommand{I}[1]{\operatorname{Im}\, (#1)}$

## Subplots and axes in matplotlib

We often want to do several plots or images on the same figure.

We can do this with the matplotlib `subplots` command.

The standard input arguments to `subplots` are the number of rows and the
number of columns you want in your grid of axes. For example, if you want two
plots underneath each other you would call `subplots(2, 1)` for two rows and
one column.

`subplots` returns a `figure` object, that is an object representing the
figure containing the axes. It also returns a list of `axes`. The axes are
objects representing the axes on which we can plot. The axis objects have
methods like `plot` and `imshow` that allow us to plot on the given axes:

```{python}
import numpy as np
import matplotlib.pyplot as plt
```

```{python}
x = np.arange(0, np.pi * 2, 0.1)
fig, axes = plt.subplots(2, 1)
axes[0].plot(x, np.sin(x))
axes[1].plot(x, np.cos(x))
```

<!-- vim:ft=rst -->
<!-- Course -->
<!-- BIC -->
<!-- Python distributions -->
<!-- Version control -->
<!-- Editors -->
<!-- Python and common libraries -->
<!-- IPython -->
<!-- Virtualenv and helpers -->
<!-- Pypi and packaging -->
<!-- Mac development -->
<!-- Windows development -->
<!-- Nipy and friends -->
<!-- FMRI datasets -->
<!-- Languages -->
<!-- Imaging software -->
<!-- Installation -->
<!-- Tutorials -->
<!-- MB tutorials -->
<!-- Ideas -->
<!-- Psych-214 -->
<!-- People -->
<!-- Licenses -->
<!-- Neuroimaging stuff -->
<!-- OpenFMRI projects -->
<!-- Unix -->
<!-- Substitutions -->
